### ISSUE TITLE
lenovo-u1-tool how to download

### ISSUE THREAD

**Issue by fire123-pl** [ASparkOfFire/lenovo-u1-tool#1]
Do you have files that U1.exe wants to download? Unfortunately, but you don't want to download anything when it starts.

**Comment by ASparkOfFire** [comment]
Hey, actually the tool is very finicky, are you sure you followed the instructions carefully? You need to follow them word to word. Also, Don't plug the USB until you start the U1.exe tool first. Give it a shot and tell me if that works.

**Comment by fire123-pl** [comment]
Hey,I get a message that I can't download files from the server, even if I downloaded links to files from the program, I could not download them, the server claimed that they do not exist, if you had the archive saved, I would ask for it to be sent.

**Comment by ASparkOfFire** [comment]
Okay I'll investigate, I'll try making a bootable USB and then will make its ISO image. Try if that works.

**Comment by fire123-pl** [comment]
It would be great if you did that

**Comment by ASparkOfFire** [comment]
So, I tried making a Bootable USB, and I'm having same issue, it doesn't wanna download, I'll try again sometime. But thanks Lenovo for making such a crappy tool.

**Comment by shekarreddyb** [comment]
Any update on this, even the lenovo service person doesn't have this working. I couldn't update my serial number

**Comment by ASparkOfFire** [comment]
> Any update on this, even the lenovo service person doesn't have this working. I couldn't update my serial number

Unfortunately, it doesn't work. Throws a "download failed" error. Maybe If someone who's good at reverse engineering, might dissect the contents of the executable and find out what it wants to download.

**Comment by shekarreddyb** [comment]
#2

**Comment by shekarreddyb** [comment]
#2
