### ISSUE TITLE
USB tool creation not working

### ISSUE THREAD

**Issue by shyyan85** [ASparkOfFire/lenovo-u1-tool#2]
When opening U1.exe and then inserting USB it gives error 'download failed'. 
Note USB has been formatted correctly by following instructions using usbfmtpw.exe.

Any help is welcomed.

**Comment by shekarreddyb** [comment]
I got it working with new version finally. I had newer u1.exe file and followed the instructions. 
https://drive.google.com/file/d/1cogC21wKj6c0zOQ48B604FNUr8WwsZKR/view?usp=sharing

**Comment by shyyan85** [comment]
That's great. 
The link you shared is only for a photo, do you have the installation file?

**Comment by shekarreddyb** [comment]
Added the zip for u1u. in the url.
follow the same instructions.
format usb with the tool with usbfmtpw.exe. (make sure to select FAT32)
eject usb
run u1u.exe
insert usb
it shows cloud version as 3.3.8.
click on Run ==> shows message 'checking' for  little longer. And finally, you get "Done" message.

**I didn't see any network calls in fiddler while this operation going on, After Finishing, the tool makes two calls to lenovo API for logging.**

Eject the drive and reconnect.
Goto windows settings "Backup and restore" -> select recovery -> advanced restart.
Select "USE a device" restart screen.
and select USB EFI again.
upon restart, you get a black screen to enter into usb. Hit any key to enter into boot screen within 5 seconds.
Select the first option in menu as shown in pictures (MTM/SN/PN/UUID flash tool)

sample command for Product name.
**uone.nsh /PN "Lenovo Y7000-2019-PG0"**
Make sure you use double quotes for value.

once you finish all MTM, PN, SN, type exit to exit command prompt screen and proceed with windows boot.

**Comment by shyyan85** [comment]
It's working. Thanks for the assist and file!

**Comment by santoslao** [comment]
> I got it working with new version finally. I had newer u1.exe file
> https://drive.google.com/drive/folders/1PedvErTlKJOWV3qTCUIf3BB4gVwzbY61?usp=sharing

file has password.
![image](https://user-images.githubusercontent.com/13845734/126811175-9afee2e2-4165-4793-8b8d-470fb390cb45.png)

**Comment by shekarreddyb** [comment]
Look at the readme file in this repo , for password.

**Comment by techguy121400** [comment]
Tool works perfect for certain models, I am getting an error with the IDEAPADS it will halt and wont update the SN,MTM,UUID, and model.

**Comment by gauravkjn** [comment]
Password
